artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Dipeshshome/DS-AI-ML-DL--IIT-Kharagpur/raw/main/Dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\Dataset\train_FD001.txt
  unzip_data_dir_2: artifacts\data_ingestion\Dataset\test_FD001.txt
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts\data_validation\relevent_data.csv
  data_path_2: artifacts\data_validation\output_test_data.csv
  

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_update.h5


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  trained_model_path: artifacts/model_trainer/model.h5
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  #test_data_path: artifacts\data_transformation\relevent_test_data.csv
  test_data_path: artifacts\data_transformation\test.csv
  model_path: artifacts\model_trainer\model.h5
  metric_file_name: artifacts/model_evaluation/metrics.json